"""Add status to SkillNode

Revision ID: a9c65533ae40
Revises: af256662e0aa
Create Date: 2026-07-04 23:15:31.922842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9c65533ae40'
down_revision: Union[str, Sequence[str], None] = 'af256662e0aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skill_nodes', sa.Column('status', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('skill_nodes', 'status')
    # ### end Alembic commands ###
