"""Add SkillNode and SkillEdge

Revision ID: af256662e0aa
Revises: 
Create Date: 2026-07-04 22:55:49.769587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af256662e0aa'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skill_nodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=False),
    sa.Column('provenance', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skill_nodes_id'), 'skill_nodes', ['id'], unique=False)
    op.create_table('skill_edges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('relationship', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['skill_nodes.id'], ),
    sa.ForeignKeyConstraint(['target_id'], ['skill_nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skill_edges_id'), 'skill_edges', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_skill_edges_id'), table_name='skill_edges')
    op.drop_table('skill_edges')
    op.drop_index(op.f('ix_skill_nodes_id'), table_name='skill_nodes')
    op.drop_table('skill_nodes')
    # ### end Alembic commands ###
